# Generated by Django 3.2 on 2023-03-30 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('team', models.CharField(choices=[('Management', 'Management'), ('WorkHorse', 'WorkHorse')], default='WorkHorse', max_length=60)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('alt_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('project_name', models.CharField(max_length=200, unique=True)),
                ('project_location', models.CharField(blank=True, choices=[('East', 'East'), ('West', 'West'), ('North', 'North'), ('South', 'South'), ('CBD', 'CBD')], max_length=30, null=True)),
                ('project_type', models.CharField(blank=True, choices=[('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Plot', 'Plot'), ('Resale', 'Resale'), ('Commercial', 'Commercial')], max_length=30, null=True)),
                ('project_completion_status', models.CharField(blank=True, choices=[('Pre-launch', 'Pre-launch'), ('Under Construction', 'Under Construction'), ('Ready to move', 'Ready to move')], max_length=30, null=True)),
                ('budget', models.CharField(blank=True, choices=[('Upto 50 lakh', 'Upto 50 lakh'), ('50 lakh - 1 crore', '50 lakh - 1 crore'), ('1 crore - 2 crore', '1 crore - 2 crore'), ('2 crore - 3 crore', '2 crore - 3 crore'), ('3 crore - 5 crore', '3 crore - 5 crore'), ('Above 5 crore', 'Above 5 crore')], max_length=30, null=True)),
                ('source', models.CharField(blank=True, choices=[('Facebook', 'Facebook'), ('Google', 'Google'), ('Reference', 'Reference'), ('CommonFloor', 'CommonFloor'), ('Other', 'Other')], max_length=30, null=True)),
                ('duplicate_lead', models.BooleanField(default=False)),
                ('date_of_enquiry', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Dropped', 'Dropped'), ('Invalid', 'Invalid'), ('Booking', 'Booking')], default='Open', max_length=30)),
                ('initial_observation', models.TextField(blank=True, null=True)),
                ('unit_number', models.CharField(blank=True, max_length=60, null=True)),
                ('agreement_value', models.PositiveIntegerField(default=0)),
                ('booking_date', models.DateField(auto_now=True)),
                ('nfs_brokerage', models.FloatField(default=0)),
                ('cashback', models.FloatField(default=0)),
                ('staff_brokerage', models.FloatField(default=0)),
                ('reminder', models.DateField(blank=True, null=True, verbose_name='Set Reminder For')),
                ('site_visit_fixed', models.BooleanField(default=False)),
                ('site_visit_done', models.BooleanField(default=False)),
                ('site_visit_date', models.DateField(blank=True, null=True)),
                ('last_followup_remarks', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('followup_remarks', models.TextField()),
                ('by', models.CharField(blank=True, max_length=60, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.lead')),
            ],
        ),
    ]
