# Generated by Django 3.2 on 2023-04-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='project_completion_status',
            field=models.CharField(blank=True, choices=[('Pre-launch', 'Pre-launch'), ('Under Construction', 'Under Construction'), ('Ready to move', 'Ready to move')], max_length=30, null=True, verbose_name='Project Completion'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='project_location',
            field=models.CharField(blank=True, choices=[('East', 'East'), ('West', 'West'), ('North', 'North'), ('South', 'South'), ('CBD', 'CBD')], max_length=30, null=True, verbose_name='Project Location'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='project_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='project_type',
            field=models.CharField(blank=True, choices=[('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Plot', 'Plot'), ('Resale', 'Resale'), ('Commercial', 'Commercial')], max_length=30, null=True, verbose_name='Project Type'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='site_visit_fixed',
            field=models.BooleanField(default=False, verbose_name='S.V'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Google', 'Google'), ('Reference', 'Reference'), ('CommonFloor', 'CommonFloor'), ('Other', 'Other')], default='Reference', max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Postpone', 'Postpone'), ('Dropped', 'Dropped'), ('Invalid', 'Invalid'), ('Booking', 'Booking')], default='Open', max_length=30),
        ),
    ]
