# Generated by Django 3.2 on 2023-08-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20230415_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='facebook_id',
            field=models.CharField(default=1, max_length=200, unique_for_date='phone'),
            preserve_default=False,
        ),
    ]
