# Generated by Django 3.2 on 2023-08-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_lead_facebook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='facebook_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
